server:
  port: 8090

spring:
application:
name: venda-ingressos-2

datasource:
url: jdbc:h2:mem:mydb
username:
password:
driverClassName: org.h2.Driver
jpa:
show-sql: true
database-platform: org.hibernate.dialect.H2Dialect